"""add roles

Revision ID: 30bac92e1aa6
Revises: f939c31d4d79
Create Date: 2024-01-20 15:38:19.207324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bac92e1aa6'
down_revision: Union[str, None] = 'f939c31d4d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users', sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default=' user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'roles')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
